### ISSUE TITLE
Add example data sets for other sampling frequencies

### ISSUE THREAD

**Issue by tmalsburg** [tmalsburg/saccades#10]
120 Hz (Tobii) and 500 Hz / 1000 Hz (EyeLink).

**Comment by MalikQasimAli** [comment]
Hi, I have data sets of Tobii 120 Hz in an Excel sheet. Shall I share it here?

**Comment by tmalsburg** [comment]
Hi Marik, how well is the algorithm working with your Tobii data?  The algorithm was designed with higher-frequency data (250+Hz) in mind and it works well for that.  I'm not sure whether I should encourage people to use it with lower-frequency data.  Although I've received reports from people who used it successfully with such data.

**Comment by MalikQasimAli** [comment]
I am new in R programming. I am trying it to figure out how to parse my data and run it.

**Comment by tmalsburg** [comment]
I recommend setting aside some time to learn the basics of R before you start processing your data.  Datacamp have a good [tutorial for beginners](https://www.datacamp.com/courses/free-introduction-to-r) (the free chapters are enough to get you started) and this free online book is a great resource once you've figured out the basics: https://r4ds.had.co.nz/  It's worth spending some
