### ISSUE TITLE
Fixation Issues

### ISSUE THREAD

**Issue by jgeller112** [tmalsburg/saccades#12]
Have you done any comparison testing with fixation reports from other trackers? I was thinking about including the saccades package functionality into my gazeR package, but I ran into some worrying results when analyzing fixation data for a VWP. The correspondence between the two was pretty low and the results didn’t look reasonable.

**Comment by tmalsburg** [comment]
Hi, of course I have done comparisons with commercial software and also many other tests to see whether the software is working as it's supposed to.  I've also used this software in many research projects over the years and never had any problems.  Usually the results with this package are similar or better than with other algorithms. In my experience, the differences between algos mostly concern the precision of fixation on- and offsets, not so much location.  The differences in your plots, imply differences in location, though (more looks to target with on algo vs the other).  Is it possible that the source of these differences is not the saccade detection algorithm but some other step in the processing pipeline?  If you believe it's the algorithm, please use the function `diagnostic.plot` to compare the results of both algorithms.  If there is a problem with the fixations produced by this package, it would be great if you could supply some sample data so I can check what's going on.

**Comment by jgeller112** [comment]
Thanks for the quick response! 

You can download sample data here: 

install_github("dmirman/gazer")

gaze <- system.file("extdata", "s2.xls", package = "gazer")
gaze_samp <- read.table(gaze)

Here is the fixation data supplied by SR:

gaze <- system.file("extdata", "f2.xls", package = "gazer")
gaze_fix <-read.table(gaze_fix)

The sccades packages seems to detect many more fixations than SR.

**Comment by jgeller112** [comment]
This is for one trial using the saccades package

![1trialsamp](https://user-images.githubusercontent.com/18429968/64891565-e250c400-d637-11e9-9647-02a10108dd5c.png)

This is for the SR data: 

![samp_SR](https://user-images.githubusercontent.com/18429968/64891982-e92c0680-d638-11e9-8fb2-4023f25de1bb.png)

**Comment by tmalsburg** [comment]
Well, the second plot apparently didn't work, so I can't compare the results.  However, the first plot (results from saccades package) looks really nice if you ask me.  At least in this limited sample, I can't see any indication that something went wrong. This strengthens my believe that the differences between the two original plots are due to some other problem in the analysis pipeline.

One question: Why do you use fixations in the first place?  Isn't it more common in visual world analyses to use the raw samples or time-binned samples (e.g., Barr, 2008)?  I don't see what fixations are buying you.  In fact they seem to only complicate the analysis.  Am I missing something?

**Comment by jgeller112** [comment]
You are right. In the gazeR package paper we will be recommending using samples instead of fixations. Some reviewers asked us to include some type of event detection algo that is not proprietary (e.g., SR), which is what brought me here. 

On a positive note, I used the saccades package for blink detection in our pupil example in the paper, and that seemed to work pretty well. 

I will keep messing around with it.

**Comment by tmalsburg** [comment]
Good to hear that blink detection is working.  That's a relatively recent addition to the package.

Since, the diagnostic plots don't show any evidence for a problem with saccade/fixation detection, I will close this issue for now.  But please don't hesitate to reopen if you find something.
