### ISSUE TITLE
Error in detect.fixations

### ISSUE THREAD

**Issue by jgeller112** [tmalsburg/saccades#13]
I am not sure if it is my computer, but running your example data 
```
data(samples)
head(samples)
fixations <- detect.fixations(samples)
```
returns this warning message: 
In max(x, na.rm = TRUE) : no non-missing arguments to max; returning -Inf
```

**Comment by jgeller112** [comment]
It also does it with other data I am process through the function.

**Comment by tmalsburg** [comment]
It’s a warning, not an error. I think it is harmless but I will have a closer look.

**Comment by jgeller112** [comment]
It doesn’t seem to have any impact on the df that is created, but figured I would let you know. I use it as part of a preprocessing pipeline and it generates a lot of warning messages.

Jason Geller, Ph.D.
Postdoctoral Scholar
Department of Psychological and Brain Sciences
The University of Iowa

On Sep 16, 2019, at 12:23 AM, Titus von der Malsburg <notifications@github.com<mailto:notifications@github.com>> wrote:

It’s a warning, not an error. I think it is harmless but I will have a closer look.

**Comment by tmalsburg** [comment]
Okay, I checked: This is happening in the calculation of the time at which events end.  If the trial ends during a blink, the blink's end time cannot be determined.  As a result you get `-Inf` as the end time.  Perhaps not the most elegant solution, and the warning is certainly annoying.  But, as you say, the results are otherwise correct. I will see how this can be improved.  Thanks for reporting.

**Comment by tmalsburg** [comment]
The warning message should no longer appear in the latest version.  Could you please confirm with your data set?  Thanks.

**Comment by jgeller112** [comment]
No more warning messages!

Thanks!

On Sep 16, 2019, at 9:32 AM, Titus von der Malsburg <notifications@github.com<mailto:notifications@github.com>> wrote:


The warning message should no longer appear in the latest version. Could you please confirm with your data set? Thanks.
