### ISSUE TITLE
Data file can be in text or tsv ?

### ISSUE THREAD

**Issue by MalikQasimAli** [tmalsburg/saccades#17]
Hi, 
Thank you for the great tool. 
I have data files in text and tsv formats. Can we use that?

**Comment by tmalsburg** [comment]
Sure, this package doesn't care about the file format.  You just have to read the data and then pass it to the function `detect.fixations` as a data frame.  See the instructions and mini tutorial on the startpage of this tutorial.  If you have data in `.tsv` format, you can read it with the function `read_tsv` from the readr package.

**Comment by MalikQasimAli** [comment]
Hi, Thank you for your reply. It worked on my CSV file. The time in my column start with "610327747" which looked like nanoseconds. Shall I convert it into ms? or what would be the best practice?
I cannot find Saccad Function. Did you integrate the Saccade algorithm?

**Comment by tmalsburg** [comment]
I doubt that these are nanoseconds (too short to be measurable with an eye-tracker).  Most eye-trackers use milliseconds which is the unit I use as well.  Check your eye-tracker's manual.

**Comment by MalikQasimAli** [comment]
Hi, I converted the time in milliseconds. Can you please help me with how can I detect Saccades?
Thanks

**Comment by tmalsburg** [comment]
@MalikQasimAli under different circumstances I'd try to help you, but things are difficult at this time with the pandemic going on, the child at home, and work piling up.  I recommend studying the example on the start page of the repository.  Your data needs to be in the same shape as the sample data and then you can just follow the code of the example.

**Comment by MalikQasimAli** [comment]
Hi, yes I run the code, and it's working. I see you have the function of detect.Saccade. Is it working?
