### ISSUE TITLE
Cannot install from github

### ISSUE THREAD

**Issue by psychmdl** [tmalsburg/saccades#18]
Thanks for making this package! I can install from CRAN, but not from github. When I try installing, I get the following error:

**Error: Failed to install 'saccades' from GitHub:
  (converted from warning) installation of package 'filepath is here' had non-zero exit status.**

I tried downloading it as a zip and then installing. When I do, I get **"Error in library(saccades) : ‘saccades’ is not a valid installed package"**

Any help would be appreciated. Thanks!!

**Comment by tmalsburg** [comment]
I just tried installing it from GitHub and it worked as expected.  Could you please post the complete output of the installation process. The info you show above is just the summary and not enough to tell what went wrong.

A note: The version on CRAN is badly outdated.  I should get it removed.  The reason why I didn't update it is because one CRAN maintainer is really difficult to deal with, and I didn't want to repeat the experience that I had when I submitted the initial version of the package.

**Comment by psychmdl** [comment]
Thank you for the reply! Here is the output when I tried to install it:

```
> install_github("tmalsburg/saccades/saccades", dependencies=TRUE)
Downloading GitHub repo tmalsburg/saccades@HEAD
√  checking for file 'C:\Users\Mark\AppData\Local\Temp\RtmpsbJhHh\remotes701476ed11f\tmalsburg-saccades-bb55d20\saccades/DESCRIPTION' ... 
-  preparing 'saccades':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'saccades_0.2-1.tar.gz'
   
* installing *source* package 'saccades' ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'zoom' was built under R version 4.0.5
Execution halted
ERROR: lazy loading failed for package 'saccades'
* removing 'D:/Program Files D/R-4.0.2/library/saccades'
Error: Failed to install 'saccades' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Mark/AppData/Local/Temp/RtmpsbJhHh/file701451c51a25/saccades_0.2-1.tar.gz’ had non-zero exit status
```

**Comment by tmalsburg** [comment]
I think you need to reinstall the `zoom` package before you install saccades.

**Comment by psychmdl** [comment]
Thanks! I just did that, and now it installs without a problem. Thank you for your help!
